# Generated by Django 4.1.7 on 2024-05-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('date', models.DateField(verbose_name='%m/%d/%Y')),
                ('created_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('updated_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=False, max_length=255)),
                ('basket_icon_click', models.IntegerField(default=False)),
                ('basket_add_list', models.IntegerField(default=False)),
                ('basket_add_detail', models.IntegerField(default=False)),
                ('sort_by', models.IntegerField(default=False)),
                ('image_picker', models.IntegerField(default=False)),
                ('account_page_click', models.IntegerField(default=False)),
                ('promo_banner_click', models.IntegerField(default=False)),
                ('detail_wishlist_add', models.IntegerField(default=False)),
                ('list_size_dropdown', models.IntegerField(default=False)),
                ('closed_minibasket_click', models.IntegerField(default=False)),
                ('checked_delivery_detail', models.IntegerField(default=False)),
                ('checked_returns_detail', models.IntegerField(default=False)),
                ('sign_in', models.IntegerField(default=False)),
                ('saw_checkout', models.IntegerField(default=False)),
                ('saw_sizecharts', models.IntegerField(default=False)),
                ('saw_delivery', models.IntegerField(default=False)),
                ('saw_account_upgrade', models.IntegerField(default=False)),
                ('saw_homepage', models.IntegerField(default=False)),
                ('device_computer', models.IntegerField(default=False)),
                ('device_tablet', models.IntegerField(default=False)),
                ('returning_user', models.IntegerField(default=False)),
                ('loc_uk', models.IntegerField(default=False)),
                ('propensity', models.FloatField(default=False)),
                ('score', models.FloatField(default=False)),
                ('created_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('updated_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
            ],
        ),
    ]
