# Generated by Django 5.0.6 on 2024-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isselect',
            name='not_select',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isselect',
            name='select',
            field=models.TextField(blank=True, null=True),
        ),
    ]
