# Generated by Django 5.0.6 on 2024-05-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_user', models.IntegerField()),
                ('max_score', models.FloatField()),
                ('min_score', models.FloatField()),
                ('number_potential_customers', models.IntegerField()),
                ('number_user_percent', models.FloatField()),
                ('max_score_percent', models.FloatField()),
                ('min_score_percent', models.FloatField()),
                ('number_potential_customers_percent', models.FloatField()),
            ],
        ),
    ]
