# Generated by Django 5.0.6 on 2024-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_simulation_created_at_alter_simulation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='updated_at',
            field=models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
    ]
