# Generated by Django 5.0.6 on 2024-05-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_simulation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crud.simulation'),
        ),
        migrations.AlterField(
            model_name='isselect',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crud.simulation'),
        ),
    ]
