# Generated by Django 5.0.6 on 2024-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_account_alter_simulation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='user_id',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='isselect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
